// prettier-ignore
// cSpell:disable
export const fontTables = {
	GlyphOrder: { id: 'GlyphOrder', name: 'Glyph Order', note: 'TTX uses this table to track glyph ordering, it is not an actual font file table.', type: '' },
	BASE: { id: 'BASE', name: 'Baseline data', type: 'advanced' },
	CBDT: { id: 'CBDT', name: 'Color bitmap data', type: 'bitmap' },
	CBLC: { id: 'CBLC', name: 'Color bitmap location data', type: 'bitmap' },
	CFF:  { id: 'CFF',  name: 'Compact Font Format 1.0', type: 'cff' },
	CFF2: { id: 'CFF2', name: 'Compact Font Format 2.0', type: 'cff' },
	COLR: { id: 'COLR', name: 'Color table', type: 'color' },
	CPAL: { id: 'CPAL', name: 'Color palette table', type: 'color' },
	DSIG: { id: 'DSIG', name: 'Digital signature', type: 'ot' },
	Debg: { id: 'Debg', name: 'Debug', type: '' },
	EBDT: { id: 'EBDT', name: 'Embedded bitmap data', type: 'bitmap' },
	EBLC: { id: 'EBLC', name: 'Embedded bitmap location data', type: 'bitmap' },
	FFTM: { id: 'FFTM', name: 'FontForge Time Stamp', type: '' },
	Feat: { id: 'Feat', name: 'Graphite Features', type: 'graphite' },
	GDEF: { id: 'GDEF', name: 'Glyph definition data', type: 'advanced' },
	GMAP: { id: 'GMAP', name: 'SING Glyphlet Summary', type: 'sing' },
	GPKG: { id: 'GPKG', name: 'SING Glyphlet Wrapper', type: 'sing' },
	GPOS: { id: 'GPOS', name: 'Glyph positioning data', type: 'advanced' },
	GSUB: { id: 'GSUB', name: 'Glyph substitution data', type: 'advanced' },
	Glat: { id: 'Glat', name: 'Graphite Glyph Attributes', type: 'graphite' },
	Gloc: { id: 'Gloc', name: 'Graphite index to glyph attributes', type: 'graphite' },
	HVAR: { id: 'HVAR', name: 'Horizontal metrics variations', type: 'variations'},
	JSTF: { id: 'JSTF', name: 'Justification data', type: 'advanced' },
	LTSH: { id: 'LTSH', name: 'Linear threshold data', type: 'ot' },
	MATH: { id: 'MATH', name: 'Math layout data', type: 'advanced' },
	META: { id: 'META', name: 'SING Glyphlet Metadata', type: 'sing' },
	MVAR: { id: 'MVAR', name: 'Metrics variations', type: 'variations' },
	OS_2: { id: 'OS_2', name: 'OS/2 and Windows specific metrics', type: 'required'},
	SING: { id: 'SING', name: 'SING Glyphlet Basic Information', type: 'sing' },
	STAT: { id: 'STAT', name: 'Style attributes', note: 'Required for variable fonts, optional for non-variable fonts', type: 'variations'},
	SVG:  { id: 'SVG',  name: 'The SVG table', type: 'svg' },
	Silf: { id: 'Silf', name: 'Graphite Rules', type: 'graphite' },
	Sill: { id: 'Sill', name: 'Graphite Languages', type: 'graphite' },
	TSI0: { id: 'TSI0', name: 'Glyph Program Text Indices', note: 'For use by the Visual TrueType program', type: 'vtt'},
	TSI1: { id: 'TSI1', name: 'Glyph Program Text UTF-8 Text Dump', note: 'For use by the Visual TrueType program', type: 'vtt'},
	TSI2: { id: 'TSI2', name: 'VTT Talk Text Indices', note: 'For use by the Visual TrueType program', type: 'vtt'},
	TSI3: { id: 'TSI3', name: 'VTT Talk UTF-8 Text Dump', note: 'For use by the Visual TrueType program', type: 'vtt'},
	TSI5: { id: 'TSI5', name: 'VTT Character Group Flag', note: 'For use by the Visual TrueType program', type: 'vtt'},
	TSIB: { id: 'TSIB', name: 'VTT BASE Table Text Source', note: 'For use by the Visual TrueType program', type: 'vtt'},
	TSIC: { id: 'TSIC', name: 'VTT Variation CVT windows source', note: 'For use by the Visual TrueType program', type: 'vtt'},
	TSID: { id: 'TSID', name: 'VTT GDEF Table Text Source', note: 'For use by the Visual TrueType program', type: 'vtt'},
	TSIJ: { id: 'TSIJ', name: 'VTT JSTF Table Text Source', note: 'For use by the Visual TrueType program', type: 'vtt'},
	TSIP: { id: 'TSIP', name: 'VTT GPOS Table Text Source', note: 'For use by the Visual TrueType program', type: 'vtt'},
	TSIS: { id: 'TSIS', name: 'VTT GSUB Table Text Source', note: 'For use by the Visual TrueType program', type: 'vtt'},
	TSIV: { id: 'TSIV', name: 'VTT table for MS VOLT', note: 'For use by the Visual TrueType program', type: 'vtt'},
	TTFA: { id: 'TTFA', name: 'ttfautohint Parameters', type: '' },
	VDMX: { id: 'VDMX', name: 'Vertical device metrics', type: 'ot' },
	VORG: { id: 'VORG', name: 'Vertical Origin', type: 'cff-optional' },
	VVAR: { id: 'VVAR', name: 'Vertical metrics variations', type: 'variations' },
	ankr: { id: 'ankr', name: 'Anchor Points', type: 'aat' },
	avar: { id: 'avar', name: 'Axis variations', type: 'variations' },
	bsln: { id: 'bsln', name: 'Baseline', type: '' },
	cidg: { id: 'cidg', name: 'CID to Glyph ID', type: 'aat' },
	cmap: { id: 'cmap', name: 'Character to glyph mapping', type: 'required' },
	cvar: { id: 'cvar', name: 'CVT variations', note: 'TrueType outlines only', type: 'variations'},
	cvt:  { id: 'cvt',  name: 'Control Value Table', note: 'Optional', type: 'tt'},
	feat: { id: 'feat', name: 'Feature names', type: 'aat' },
	fpgm: { id: 'fpgm', name: 'Font program', note: 'Optional', type: 'tt' },
	fvar: { id: 'fvar', name: 'Font variations', type: 'variations' },
	gasp: { id: 'gasp', name: 'Grid-fitting / Scan-conversion', note: 'Optional', type: 'tt'},
	gcid: { id: 'gcid', name: 'Glyph ID to CID', type: 'aat' },
	glyf: { id: 'glyf', name: 'Glyph data', type: 'tt' },
	gvar: { id: 'gvar', name: 'Glyph variations', note: 'TrueType outlines only', type: 'variations'},
	hdmx: { id: 'hdmx', name: 'Horizontal device metrics', type: 'ot' },
	head: { id: 'head', name: 'Font header', type: 'required' },
	hhea: { id: 'hhea', name: 'Horizontal header', type: 'required' },
	hmtx: { id: 'hmtx', name: 'Horizontal metrics', type: 'required' },
	kern: { id: 'kern', name: 'Kerning', type: 'ot' },
	lcar: { id: 'lcar', name: 'Ligature Carets', type: '' },
	loca: { id: 'loca', name: 'Index to location', type: 'tt' },
	ltag: { id: 'ltag', name: 'Language Tags', type: '' },
	maxp: { id: 'maxp', name: 'Maximum profile', type: 'required' },
	meta: { id: 'meta', name: 'Metadata', type: 'ot' },
	mort: { id: 'mort', name: 'Glyph Metamorphosis', type: '' },
	morx: { id: 'morx', name: 'Extended Glyph Metamorphosis', type: '' },
	name: { id: 'name', name: 'Naming table', type: 'required' },
	opbd: { id: 'opbd', name: 'Optical Bounds', type: '' },
	post: { id: 'post', name: 'PostScript information', type: 'required' },
	prep: { id: 'prep', name: 'CVT Program', note: 'Optional', type: 'tt' },
	prop: { id: 'prop', name: 'Glyph Properties', type: '' },
	sbix: { id: 'sbix', name: 'Standard bitmap graphics', type: 'bitmap' },
	trak: { id: 'trak', name: 'Tracking', type: '' },
	vhea: { id: 'vhea', name: 'Vertical Metrics header', type: 'ot' },
	vmtx: { id: 'vmtx', name: 'Vertical Metrics', type: 'ot' },
};
